### ISSUE TITLE
HKMP not registering skin spell effects.

### ISSUE THREAD

**Issue by xXDJBaconXx** [Extremelyd1/HKMP#18]
This might be the lowest of your priorities, but it looks like it only reads the sprint and sprite sheets.
Any plans on having it read the other sheets included in skin files?

**Comment by Extremelyd1** [comment]
It only uses the Knight and Sprint sprite sheets at the moment. I believe there is already a suggestion to include the other sprite sheets as well in the Discord server (which can be found in the readme). They are not as trivial to implement however, and as you correctly point out, not a high priority.
I don't really use Github issues for general suggestions/bug reports as the Discord server already hosts those. So feel free to join the Discord server if you are interested. For now, I'll close this issue.
