### ISSUE TITLE
Some asks from lil' russian pupil 

### ISSUE THREAD

**Issue by Dukeofhollow** [Extremelyd1/HKMP#33]
Nothing important I just want to say that is your mod is awesome and stable and ask. Is it possible to make skins effects like slash or fireball and HUD are dependent from chosen in hkmp skin? And I want to know how many problems bring enemy sync? How many time it will take if you start work without any rest like eat or sleep?

>

**Comment by Extremelyd1** [comment]
First of all, Github issues are mostly meant for codebase-related inquiries, which this one is not. Please join the [Discord server](https://discord.gg/KbgxvDyzHP) for these kinds of questions.

Let me quickly answers them anyway:
>  Is it possible to make skins effects like slash or fireball and HUD are dependent from chosen in hkmp skin?

This is a suggested feature already, but has not yet been implemented.

> I want to know how many problems bring enemy sync?

The entity system (in its current stage) requires an implementation per entity, which Hollow Knight has 150+ of. This is a substantial amount of work and will not be finished anytime soon.
