### ISSUE TITLE
Disconnect causes shade soul to stop working after casting descending dark

### ISSUE THREAD

**Issue by flarespeed** [Extremelyd1/HKMP#42]
steps to reproduce:
1. connect to server
2. disconnect from server
3. cast descending dark
4. attempt to cast shade soul
The animation of shade soul will play but soul will not be consumed and no projectile will be cast.

**Comment by flibber-hk** [comment]
Similar bug with Shriek - the shriek effect happens but the airstall duration seems to be reduced (to zero?) 
DDarking causes the bug - it seems that it happens even if you exit and re-enter the file (no need to connect/disconnect after re-entering the file, though you need to ddark again)

**Comment by Extremelyd1** [comment]
Fixed in e373a8dd406f2dce1a70889a1bef592c0be3f14f
