### ISSUE TITLE
Enemy Sync when

### ISSUE THREAD

**Issue by AlexiaTheLonely** [Extremelyd1/HKMP#46]
I and my friend have been using this mod lately, and we noticed that enemies don't sync, thinking it was a bug i removed and reinstalled the mod, seeing it wouldn't fix i checked the wiki and saw there is none, so, is there going to be an enemy sync?

**Comment by Extremelyd1** [comment]
Github issues are mostly meant for codebase-related inquiries, which this one is not. Please join the [Discord server](https://discord.gg/KbgxvDyzHP) for these kinds of questions.

In short, progress is being made on implementing an entity system, but it will not be finished in the near future.
