### ISSUE TITLE
Docker Version

### ISSUE THREAD

**Issue by maximalmax90** [Extremelyd1/HKMP#70]
Issued the Standalone version in the container for docker fans. Maybe someone will need it. Images are assembled and uploaded on [DockerHub](https://hub.docker.com/repository/docker/maximalmax90/hkmpserver). Sources uploaded on [GitHub](https://github.com/maximalmax90/HKMPDocker).

**Comment by maximalmax90** [comment]
Updated image and source files of container to work with new release.

**Comment by Extremelyd1** [comment]
I'm not a big fan of this being an issue, given that it is only informational. I'll close it for now, but feel free to PR the README to add it in there.
