### ISSUE TITLE
Support non-ASCII characters for usernames and chat

### ISSUE THREAD

**Issue by mufeng233** [Extremelyd1/HKMP#89]
Requirement: Chinese cannot be entered in the chat box. Could you please add Chinese support? And although you can set Chinese nickname, but in the chat box to input something to send is, the name will show two question marks, hope you can fix it. I'm sorry if the translation I used was inaccurate.

**Comment by Extremelyd1** [comment]
Initial changes to accommodate this enhancement in: 3a9bb1824e34f47ebcb02a443a5be1befffd76d5
Needs further testing still.

**Comment by Extremelyd1** [comment]
Implemented in c42a2e67aaa4261417f167d3b93b33ecb32e0e7e
