### ISSUE TITLE
Cant collect Useables? (mantas claws and such)

### ISSUE THREAD

**Issue by C0dename1701** [Extremelyd1/HKMP#97]
When pplaying i cant collect items mainly the mantus claws, is this a known issue

**Comment by Extremelyd1** [comment]
It is highly unlikely that this is caused by HKMP as it does not modify the behaviour in any way. Please join the [Discord server](https://discord.gg/KbgxvDyzHP) for support. Refrain from making Github issues unless they are related to the code or you are sure it is a bug-report.
