### ISSUE TITLE
Npcs not working properly

### ISSUE THREAD

**Issue by avocadopunched** [Extremelyd1/HKMP#99]
both me and my friend have broken the fragile strength charm in our multiplayer world and have been unable to repair it. leg eater does not give the "repair charm" prompt and only responds saying he has nothing left to show(we bought all the fragile charms). similarly, iselda also does this despite us never having bought her map pins. is there anyway to fix this, or at least a command to restore the charm?

**Comment by Extremelyd1** [comment]
I'm fairly certain this is not caused by HKMP and will most likely be because of other mods you have installed. If you have reason to believe otherwise, please provide reproduction info on this issue.
